### ISSUE TITLE
你的数据文件怎么产生的？比如vobca.txt sentences.txt??

### ISSUE THREAD

**Issue by northeast250** [leehour/Seq2SeqWithPGN#1]
(py38nlp) ➜  /Users/admin/Seq2SeqWithPGN python build_vocab.py    
Traceback (most recent call last):
  File "build_vocab.py", line 29, in <module>
    vocab, reverse_vocab = generate_vocab(sentences_path)
  File "build_vocab.py", line 8, in generate_vocab
    sentences = read_lines(sentence_path)
  File "/Users/admin/Seq2SeqWithPGN/utils/data_utils.py", line 34, in read_lines
    with open(path, mode='r', encoding='utf-8') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/admin/Seq2SeqWithPGN/datasets/sentences.txt'

**Comment by leehour** [comment]
先运行train_word_vec.py 和build_vocab.py生成这两个文件，train_word_vec.py里面记得把注释打开以生成sentences.txt
